---
- hosts: 127.0.0.1
  roles:
    - bt5e.docker_ce
    - bt5e.docker_compose
    - { role: bt5e.docker-non-root-user, non_root_docker_users: vagrant }
    - bt5e.kubectl
    - bt5e.k8s_helm
    - bt5e.google_cloud_sdk

  tasks:
    - name: Install packages via yum
      yum:
        name:
          - "python3-pip"
        state: latest
      become: yes
