- src: bt5e.docker_ce
  version: v19.3.12

- src: bt5e.docker_compose
  version: v1.26.2

- src: bt5e.docker-non-root-user

- src: bt5e.kubectl

- src: bt5e.k8s_helm
  version: v3.3.0

- src: bt5e.google_cloud_sdk
